DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS jobs;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE jobs (
  id SERIAL PRIMARY KEY,
  company   VARCHAR NOT NULL,
  position  VARCHAR NOT NULL,
  location VARCHAR NOT NULL,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
