DROP TABLE IF EXISTS listers;
DROP TABLE IF EXISTS jobs;

CREATE TABLE listers (
  id SERIAL PRIMARY KEY,
  firstname VARCHAR(25) NOT NULL,
  lastname VARCHAR(25) NOT NULL,
  address VARCHAR NOT NULL,
  phonenumber VARCHAR NOT NULL,
  socialmedia VARCHAR,
  email VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE jobs (
  id SERIAL PRIMARY KEY,
  company   VARCHAR NOT NULL,
  position  VARCHAR NOT NULL,
  location VARCHAR NOT NULL,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
